### ISSUE TITLE
Won't install on 6.3.3

### ISSUE THREAD

**Issue by tobiz** [tonybeltramelli/ExportSQLite#1]
MySQL Workbench 6.3.3 says "lua not supported in this version".  If this plugin is to be useful in the future it needs to work with 6.3.3 and beyond.

**Comment by tonybeltramelli** [comment]
Hi tobiz,

First of all, thank you for your interest in this open source project. This Lua script was implemented and tested with MySQLWorkbench 5.2.36 and might obviously not work with the newer versions.
Since the project is open source, you are more than welcome to update it and share your work with the developer community.

Cheers,
Tony
